'use client';
import {useState,type FormEvent} from 'react';
import {supabase} from '@/lib/supabase';
import {normalizeSaPhone} from '@/lib/pin-auth';
export default function TestRegistration(){
 const [phone,setPhone]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const enabled=process.env.NEXT_PUBLIC_SUPABASE_URL==='https://faytrobauwibxujvmbct.supabase.co';
 async function register(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const normalized=normalizeSaPhone(phone),credential=password;const response=await fetch('/api/uat/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:normalized,password:credential,code})});const data=await response.json();if(!response.ok)throw new Error(data.error);const result=await supabase.auth.signInWithPassword({phone:normalized,password:credential});if(result.error)throw new Error('Account created. Return to sign in with your password.');window.location.href='/';}catch(e){setError(e instanceof Error?e.message:'Could not register.');}finally{setBusy(false);}}
 if(!enabled)return <main className="auth-shell"><h1>Not available</h1></main>;
 return <main className="auth-shell"><section className="auth-card"><a href="/">← Sign in</a><h1>Create a UAT account</h1><p>Test accounts only. No SMS or real charges. Choose a synthetic number between <b>0600000000 and 0600000099</b>. Use test code <b>123456</b>.</p><form onSubmit={register}><label htmlFor="test-phone">Test phone number</label><input id="test-phone" value={phone} onChange={e=>setPhone(e.target.value)} inputMode="numeric" pattern="06000000[0-9]{2}" required/><label htmlFor="test-code">Test code</label><input id="test-code" value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" pattern="123456" required/><label htmlFor="test-password">Choose a password</label><input id="test-password" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required/>{error&&<p role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy?'Creating…':'Create test account'}</button></form><p>Existing accounts keep their current password. This page cannot reset an existing account.</p></section></main>;
}
