'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {supabase} from '@/lib/supabase';
import SecondaryShell from '../../SecondaryShell';
import '../sports.css';
import './admin.css';
type Row={id:string;[key:string]:any};
type Data={userId:string;superAdmin:boolean;roles:Row[];schools:Row[];teams:Row[];editableTeamIds:string[];players:Row[];roster:{team_id:string;player_id:string}[];matches:Row[];assignments:Row[];users:{id:string;label:string}[];audit:Row[]};
export default function SportsAdmin(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[section,setSection]=useState('Fixtures'),[selected,setSelected]=useState('');
 const call=useCallback(async(body?:unknown)=>{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Sign in to manage sports.');const r=await fetch('/api/sports/admin',{method:body?'POST':'GET',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw new Error(result.error);return result;},[]);
 const load=useCallback(async()=>{try{setData(await call());setError('');}catch(e){setError((e as Error).message);}},[call]);
 useEffect(()=>{void load();},[load]);
 async function save(e:FormEvent<HTMLFormElement>,action:string,extra:Record<string,unknown>={}){e.preventDefault();setBusy(true);setError('');setMessage('');const form=e.currentTarget;const payload:Record<string,unknown>={...Object.fromEntries(new FormData(form)),...extra};if(payload.starts_at)payload.starts_at=new Date(String(payload.starts_at)).toISOString();payload.publish=payload.publish==='on';try{await call({action,payload});setMessage('Saved. Sports updates will appear automatically.');await load();form.reset();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function action(action:string,payload:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{await call({action,payload});setMessage('Saved.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const teamName=(id:string)=>data?.teams.find(t=>t.id===id)?.name||'Team',schoolName=(id:string)=>data?.schools.find(s=>s.id===id)?.name||'All schools';
 const owned=data?.teams.filter(t=>data.editableTeamIds.includes(t.id))||[],match=data?.matches.find(m=>m.id===selected);
 const roster=match?data?.players.filter(p=>data.roster.some(r=>r.player_id===p.id&&[match.home_team_id,match.away_team_id].includes(r.team_id)))||[]:[];
 const schoolOptions=data?.schools.filter(s=>data.superAdmin||data.roles.some(r=>r.role==='school_admin'&&r.school_id===s.id))||[];
 function teamSelect(name:string,items=owned){return <select name={name} required defaultValue=""><option value="" disabled>Select team</option>{items.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select>;}
 return <SecondaryShell active="sports"><header className="secondary-hero"><div><span className="secondary-eyebrow">Sports administration</span><h1 className="secondary-title">Keep school sport moving.</h1><p className="secondary-lead">Arrange fixtures, manage teams and players, and confirm results.</p><a href="/sports">← View Sports</a></div></header>{error&&<p className="message error" role="alert">{error}</p>}{message&&<p className="message" role="status">{message}</p>}{!data?<p><a href="/">Sign in</a> with an assigned admin account.</p>:<>
 <p className="secondary-muted">{data.superAdmin?'Super admin · all schools':`Assigned access · ${data.roles.map(r=>`${r.role==='school_admin'?'School manager':r.role} — ${schoolName(r.school_id)}`).join(', ')}`}</p>
 <nav className="project-filter" aria-label="Admin sections">{['Fixtures','Results','Teams','Players',...(data.superAdmin?['Access']:[]),'Audit'].map(s=><button key={s} className={section===s?'active':''} onClick={()=>{setSection(s);setMessage('');}}>{s}</button>)}</nav>
 {section==='Teams'&&<section className="secondary-card"><h2>Create a team</h2><form className="sports-admin-form" onSubmit={e=>save(e,'team_create')}><label>School<select name="school_id" required>{schoolOptions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Team name<input name="name" required maxLength={100}/></label><label>Sport<select name="sport"><option value="football">Football</option><option value="netball">Netball</option><option value="rugby">Rugby</option></select></label><label>Age group<input name="age_group" defaultValue="U19" required maxLength={30}/></label><label>Category<select name="gender"><option value="mixed">Mixed</option><option value="boys">Boys</option><option value="girls">Girls</option></select></label><label>Season<input name="season_year" type="number" defaultValue={new Date().getFullYear()} min="2026" max="2200" required/></label><button disabled={busy||!schoolOptions.length}>Create team</button></form><h3>Your teams</h3>{owned.map(t=><p key={t.id}>{t.name} · {t.sport} · {t.age_group} · {t.season_year}</p>)}</section>}
 {section==='Players'&&<section className="secondary-card"><h2>Add player to a team</h2><form className="sports-admin-form" onSubmit={e=>save(e,'player_create')}><label>Team{teamSelect('team_id')}</label><label>First name<input name="first_name" required maxLength={70}/></label><label>Surname<input name="last_name" required maxLength={70}/></label><label>Position<input name="position" maxLength={70}/></label><label>Shirt number<input type="number" name="shirt_number" min="0" max="999"/></label><label className="sports-admin-check"><input type="checkbox" name="publish"/> Publish profile: I confirm the required player/guardian permission has been obtained.</label><button disabled={busy}>Add player</button></form><p>Profiles stay private unless publication is confirmed.</p></section>}
 {section==='Fixtures'&&<><section className="secondary-card"><h2>Arrange a fixture</h2><form className="sports-admin-form" onSubmit={e=>save(e,'fixture_create')}><label>Home team{teamSelect('home_team_id',data.teams)}</label><label>Away team{teamSelect('away_team_id',data.teams)}</label><label>Kick-off (your local time)<input name="starts_at" type="datetime-local" required/></label><label>Venue<input name="venue" required maxLength={160}/></label><button disabled={busy}>Create fixture</button></form></section><h2>Scheduled fixtures</h2>{data.matches.filter(m=>m.status==='scheduled').map(m=><article className="secondary-card" key={m.id}><h3>{teamName(m.home_team_id)} vs {teamName(m.away_team_id)}</h3><p>{new Date(m.starts_at).toLocaleString('en-ZA',{timeZone:'Africa/Johannesburg'})} SAST · {m.venue}</p><form className="sports-admin-form" onSubmit={e=>save(e,'fixture_update',{id:m.id,revision:m.revision,home_team_id:m.home_team_id,away_team_id:m.away_team_id})}><label>New kick-off (your local time)<input type="datetime-local" name="starts_at" required/></label><label>Venue<input name="venue" defaultValue={m.venue} maxLength={160}/></label><button disabled={busy}>Reschedule</button></form></article>)}</>}
 {section==='Results'&&<section className="secondary-card"><h2>Record and confirm results</h2><label>Match<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select match</option>{data.matches.map(m=><option key={m.id} value={m.id}>{teamName(m.home_team_id)} vs {teamName(m.away_team_id)} · {m.status}</option>)}</select></label>{match&&<><p>{match.home_score} – {match.away_score} · {match.status.replace('_',' ')}</p>{match.status!=='official'&&<><h3>Record a match event</h3><form className="sports-admin-form" onSubmit={e=>save(e,'event_add',{id:match.id,revision:match.revision})}><label>Team{teamSelect('team_id',owned.filter(t=>[match.home_team_id,match.away_team_id].includes(t.id)))}</label><label>Player<select name="player_id" required>{roster.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></label><label>Event<select name="event_type">{['goal','netball_goal','assist','yellow_card','red_card','substitution'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select></label><label>Minute<input name="minute" type="number" min="0" max="200"/></label><button disabled={busy||!roster.length}>Add event</button></form><h3>Submit result</h3><form className="sports-admin-form" onSubmit={e=>save(e,'result_submit',{id:match.id,revision:match.revision})}><label>Submitting team{teamSelect('team_id',owned.filter(t=>[match.home_team_id,match.away_team_id].includes(t.id)))}</label><label>Home score<input name="home_score" type="number" min="0" max="300" required defaultValue={match.home_score}/></label><label>Away score<input name="away_score" type="number" min="0" max="300" required defaultValue={match.away_score}/></label><label>Player of the Match<select name="player_of_match_id"><option value="">Not selected</option>{roster.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></label><button disabled={busy}>Submit for confirmation</button></form></>}{match.status==='pending_confirmation'&&<><p>An opposing-school administrator or another super admin must confirm this result. You cannot confirm your own submission.</p><button className="primary" disabled={busy||match.submitted_by===data.userId} onClick={()=>action('result_confirm',{id:match.id,revision:match.revision})}>Confirm result</button></>}{match.status==='official'&&<p>This result is confirmed and locked.</p>}</>}</section>}
 {section==='Access'&&data.superAdmin&&<section className="secondary-card"><h2>Assign admin access</h2><p>For a multi-school manager, add a school-manager assignment for each school they manage. Only super admins can change access.</p><form className="sports-admin-form" onSubmit={e=>save(e,'grant')}><label>Registered account<select name="user_id" required>{data.users.map(u=><option key={u.id} value={u.id}>{u.label} · {u.id.slice(0,8)}</option>)}</select></label><label>Role<select name="role"><option value="school_admin">School manager</option><option value="coach">Coach</option><option value="super_admin">Super admin</option></select></label><label>School (manager or coach)<select name="school_id"><option value="">All schools (super admin only)</option>{data.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Team (coach only)<select name="team_id"><option value="">No team</option>{data.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button disabled={busy}>Grant access</button></form><h3>Active assignments</h3>{data.assignments.map(a=><div className="secondary-row" key={a.id}><span>{data.users.find(u=>u.id===a.user_id)?.label||a.user_id.slice(0,8)} · {a.role==='school_admin'?'School manager':a.role} · {schoolName(a.school_id)}</span><button disabled={busy||a.user_id===data.userId} onClick={()=>action('revoke',{id:a.id})}>Revoke</button></div>)}</section>}
 {section==='Audit'&&<section className="secondary-card"><h2>Change history</h2><p>Successful admin changes are recorded in the same transaction.</p>{data.audit.map(a=><div className="secondary-row" key={a.id}><span>{a.action.replace('_',' ')} · {a.entity_type} · {a.actor_user_id?.slice(0,8)}</span><time>{new Date(a.created_at).toLocaleString('en-ZA',{timeZone:'Africa/Johannesburg'})}</time></div>)}{!data.audit.length&&<p>No changes recorded yet.</p>}</section>}
 </>}</SecondaryShell>;
}
